### ISSUE TITLE
cloud-provider-payment8001的entities呢

### ISSUE THREAD

**Issue by w245836289** [leelovejava/cloud2020#21]
没发现cloud-provider-payment8001的entities

**Comment by leelovejava** [comment]
在cloud-api-common的模块
`<dependency>
            <groupId>com.atguigu.springcloud</groupId>
            <artifactId>cloud-api-common</artifactId>
            <version>${project.version}</version>
        </dependency>
`

**Comment by leelovejava** [comment]
在cloud-api-common模块

**Comment by leelovejava** [comment]
pom需要依赖`cloud-api-common`
