### ISSUE TITLE
maven导入的时候,组件提示找不到

### ISSUE THREAD

**Issue by whiteS18** [leelovejava/cloud2020#23]
<plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <fork>true</fork>
                    <addResources>true</addResources>
                </configuration>
            </plugin>

提示 spring-boot-maven-plugin提示找不到

**Comment by leelovejava** [comment]
我是可以的,你确认一下maven问题或springboot的依赖,不行就手动指定版本version.
可以去看看别的博客,[Maven插件系列之spring-boot-maven-plugin](https://www.cnblogs.com/jpfss/p/11098740.html)
