### ISSUE TITLE
请问你加了@GlobalTransactional注解后报错吗

### ISSUE THREAD

**Issue by JeffreyDai** [leelovejava/cloud2020#8]
我加了@GlobalTransactional这个注解后， orderDao.create(order);调用就包插入语句错误了，去掉注解就正常。

**Comment by leelovejava** [comment]
如果还未解决,把错误信息贴出来
`com.atguigu.springcloud.alibaba.service.impl.AccountServiceImpl`

`// 模拟超时异常,全局事务回滚
try {
    // 暂停20秒钟
    TimeUnit.SECONDS.sleep(20);
} catch (InterruptedException e) {
    e.printStackTrace();
}`

**Comment by leelovejava** [comment]
看下这个类的如下代码,如果还未解决,把错误信息贴出来
`com.atguigu.springcloud.alibaba.service.impl.AccountServiceImpl`

模拟超时异常,全局事务回滚
`try {
    TimeUnit.SECONDS.sleep(20);
} catch (InterruptedException e) {
    e.printStackTrace();
}`
